### ISSUE TITLE
course item feature

### ISSUE THREAD

**Issue by W2AlharbiMe** [TuwaiqLearningPlatform/learning-platform#7]
this feature includes:
1. search for keyword in a course item title
2. setup the relation with course

**Comment by W2AlharbiMe** [comment]
there are multiple ways to persist a json. so far the best way would be to create two methods within the `CourseItem`.

1. the first method would serialize `List<HashMap<String, Object>>` into a json string and store the string.
2. the second method would convert back or  **deserialize** from JSON string to `List<HashMap<String, Object>>`.


example:

```java
// when adding a new content
List<HashMap<String, Object>> content = new List<>();


// content 1
HashMap<String, Object> firstVideo = new HashMap<>();

firstVideo.put("path", "/path/to/video");
firstVideo.put("title", "What's Python");
firstVideo.put("duration", "5:00 minutes");

content.add(firstVideo);


// when saving the data
courseItem.setContent(content);


// when retrieving the content
List<HashMap<String, Object>> retrievedContent = courseItem.getContent();
```


example of the look of the data that will be stored:
```json
[
  {
    "path": "/path/to/video",
    "title": "What's Python",
    "duration": "5:00 minutes"
  }
]
```





@BLANK-13

**Comment by BLANK-13** [comment]
Perfect, we also need to setup the file system and store videos of these items.
